# NOTE: The same script is also included in the "apim" folder, as it is a generic script that can be used with any OpenAI endpoint but also with Azure API Management (APIM) service.

# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api


# OpenAI Endpoints:
# - OpenAI main:     {{azure_openai_main_endpoint}}, {{azure_openai_main_apikey}}
# - OpenAI fallback: {{azure_openai_fallback_endpoint}}, {{azure_openai_fallback_apikey}}
# - APIM:            {{apim_service_gatewayurl}}/{{apim_api_name}}/, {{apim_subscription_key_premium}}

@azure_openai_endpoint = {{azure_openai_main_endpoint}}
@azure_openai_apikey   = {{azure_openai_main_apikey}}

###
# Invoking OpenAI
POST {{azure_openai_endpoint}}openai/deployments/{{azure_openai_deployment_name}}/chat/completions?api-version={{azure_openai_api_version}}
Api-Key: {{azure_openai_apikey}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "what is the nuclear fusion? explain in less than 15 words"
        }
    ]
}