# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az login --use-device-code --tenant <your-tenant-id-or-domain>
# az config set extension.dynamic_install_allow_preview=true
# az account tenant list --output table
# for Azure Management tasks --> az account get-access-token --resource https://management.core.windows.net/
# for OpenAI tasks --> az account get-access-token --resource https://cognitiveservices.azure.com/
# for Azure Search tasks --> az account get-access-token --resource https://search.azure.com/
# for Machine Learning tasks --> az account get-access-token --resource https://ml.azure.com/ 

# OpenAI Endpoints:
# - OpenAI main:     {{azure_openai_main_endpoint}}
# - OpenAI fallback: {{azure_openai_fallback_endpoint}}
# - APIM:            {{apim_service_gatewayurl}}/{{apim_api_name}}/, BUT App Registration in Entra ID is needed

@azure_openai_endpoint = {{azure_openai_main_endpoint}}

###
# Invoking OpenAI
POST {{azure_openai_endpoint}}openai/deployments/{{azure_openai_deployment_name}}/chat/completions?api-version={{azure_openai_api_version}}
Authorization: Bearer {{bearertoken_for_cognitiveservices}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "what is the nuclear fusion? explain in less than 20 words"
        }
    ]
}