# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az login --use-device-code --tenant <your-tenant-id-or-domain>
# az config set extension.dynamic_install_allow_preview=true
# az account tenant list --output table
# for Azure Management tasks --> az account get-access-token --resource https://management.core.windows.net/
# for OpenAI tasks --> az account get-access-token --resource https://cognitiveservices.azure.com/
# for Azure Search tasks --> az account get-access-token --resource https://search.azure.com/
# for Machine Learning tasks --> az account get-access-token --resource https://ml.azure.com/ 

@agents-service_endpoint = https://eastus.api.azureml.ms/agents/v1.0/subscriptions/*****/resourceGroups/mmai04-rg/providers/Microsoft.MachineLearningServices/workspaces/mmai-hub04-prj01-fvye


@thread_id = thread_QfQz8A5b1In1fIrKwwEAH216

@agent_id = asst_A0UWDQ9zsQ5QbIQJT7lMp2bF


# create thread id, given the project
POST {{agents-service_endpoint}}/threads?api-version=2024-12-01-preview
Authorization: Bearer {{bearertoken_for_azureml}}
Content-Type: application/json

{}

###

# add a message to the thread, given the thread id
POST {{agents-service_endpoint}}/threads/{{thread_id}}/messages?api-version=2024-12-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "role": "user",
    "content": "Cosa posso vedere in TV stasera"
}


###
# run the thread, given the thread id and the agent id
POST {{agents-service_endpoint}}/threads/{{thread_id}}/runs?api-version=2024-12-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "assistant_id": "{{agent_id}}"
}

###
# retrieve the run_id from the previous response

@run_id = run_9IJVEy7dDcndG0sPGPAYA8lV
###
# get the run, given the thread id and the run id
GET {{agents-service_endpoint}}/threads/{{thread_id}}/runs/{{run_id}}?api-version=2024-12-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

###
# invoke the agent via local HTTP endpoint for OpenAI
POST http://localhost:5004/chat/openai
Content-Type: application/json

{
    "input": "Never mind the weather, how's the food?"
}

###
# invoke the agent via local HTTP endpoint for Foundry
POST http://localhost:5004/chat/foundry
Content-Type: application/json

{
    "input": "Which animal is known for building dams?"
}
