@azure_deployment_name = gpt-4o
@openai_api_version = 2025-03-01-preview

###
# Invoking OpenAI
POST {{openai_endpoint}}/openai/deployments/{{azure_deployment_name}}/chat/completions?api-version={{openai_api_version}}
Api-Key: {{openai_api_key}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "What is a meaning function? Please summarize in less than 20 words."
        }
    ]
}


###
# Get the list of available models, regardless of being deployed or not
GET {{openai_endpoint}}/openai/models?api-version={{openai_api_version}}
Api-Key: {{openai_api_key}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "What is a meaning function? Please summarize in less than 20 words."
        }
    ]
}

###
# Get the list of deployed models
GET {{openai_endpoint}}/openai/deployments?api-version={{openai_api_version}}&$filter=properties/status eq 'Succeeded'
Api-Key: {{openai_api_key}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "What is a meaning function? Please summarize in less than 20 words."
        }
    ]
}