# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az account get-access-token --resource https://cognitiveservices.azure.com/

@token = 

@azure_deployment_name = gpt-4o
@openai_api_version = 2025-03-01-preview

###
# Invoking OpenAI
POST {{AZURE_OPENAI_ENDPOINT}}/openai/deployments/{{azure_deployment_name}}/chat/completions?api-version={{openai_api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "What is a meaning function? Please summarize in less than 20 words."
        }
    ]
}
