# Azure Search Tests

@subscription_id = *****
@resource_group_name = mmai01-rg
@azure_search_endpoint = https://*****.search.windows.net
@aisearch_api_version = 2024-07-01
@aisearch_key = *****
@datasource_name = *****
@index1_name = *****
@indexer1_name = *****
@storage_account_name = *****
@container_name = *****
@storage_account_key = *****
@storage_connection_string = DefaultEndpointsProtocol=https;AccountName={{storage_account_name}};AccountKey={{storage_account_key}};EndpointSuffix=core.windows.net

### DataSource creation with dataChangeDetectionPolicy and dataDeletionDetectionPolicy
PUT {{azure_search_endpoint}}/datasources/{{datasource_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}

{  
    "name": "{{datasource_name}}",
    "type": "azureblob",
    "credentials": {  
        "connectionString": "ResourceId=/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group_name}}/providers/Microsoft.Storage/storageAccounts/{{storage_account_name}};"
    },
    "container": {  
        "name": "{{container_name}}"
    },
    "dataChangeDetectionPolicy": {  
        "@odata.type": "#Microsoft.Azure.Search.HighWaterMarkChangeDetectionPolicy",
        "highWaterMarkColumnName": "metadata_storage_last_modified"  
    },
    "dataDeletionDetectionPolicy": {
        "@odata.type": "#Microsoft.Azure.Search.NativeBlobSoftDeleteDeletionDetectionPolicy"
    }
}


### Create an Index
PUT {{azure_search_endpoint}}/indexes/{{index1_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}

{
  "name": "{{index1_name}}",
  "fields": [    
    {
      "name": "id",
      "type": "Edm.String",
      "key": "true",
      "searchable": "false",
      "retrievable": "true",
      "sortable": "false",
      "filterable": "false",
      "facetable": "false"
    },
    {
      "name": "title",
      "type": "Edm.String",
      "searchable": "true",
      "retrievable": "true",
      "facetable": "false",
      "filterable": "true",
      "sortable": "false"
    },
    {
      "name": "name", 
      "type": "Edm.String", 
      "searchable": "true", 
      "retrievable": "true", 
      "sortable": "false", 
      "filterable": "false", 
      "facetable": "false"
    },
    {
      "name": "location", 
      "type": "Edm.String", 
      "searchable": "true", 
      "retrievable": "true", 
      "sortable": "false", 
      "filterable": "false", 
      "facetable": "false"
    },
    {
      "name": "content",
      "type": "Edm.String",
      "searchable": "true",
      "retrievable": "true",
      "sortable": "false",
      "filterable": "false",
      "facetable": "false"
    }
  ]
}


### Create an Indexer
PUT {{azure_search_endpoint}}/indexers/{{indexer1_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}

{
  "name": "{{indexer1_name}}",
  "dataSourceName": "{{datasource_name}}",
  "targetIndexName": "{{index1_name}}",
  "fieldMappings": [
        {
          "sourceFieldName" : "metadata_title",
          "targetFieldName" : "title"
        },
        {
          "sourceFieldName" : "metadata_storage_name",
          "targetFieldName" : "name"
        },
        {
          "sourceFieldName" : "metadata_storage_path",
          "targetFieldName" : "location"
        }
    ]
}

### Re-run the Indexer
POST {{azure_search_endpoint}}/indexers/{{indexer1_name}}/run?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}


### HIC SUNT LEONES ------------------------------------

### Get all datasources
GET  {{azure_search_endpoint}}/datasources?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}



### Delete a DataSource
DELETE  {{azure_search_endpoint}}/datasources/{{datasource_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}


### Delete an Index
DELETE {{azure_search_endpoint}}/indexes/{{index1_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}


### Delete an Indexer
DELETE {{azure_search_endpoint}}/indexers/{{indexer1_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}


### Simple DataSource creation
PUT {{azure_search_endpoint}}/datasources/{{datasource_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}

{  
    "name": "{{datasource_name}}",
    "type": "azureblob",
    "credentials": {  
        "connectionString": "{{storage_connection_string}}"
    },
    "container": {  
        "name": "{{container_name}}"
    }
}



### DataSource creation with dataChangeDetectionPolicy
PUT {{azure_search_endpoint}}/datasources/{{datasource_name}}?api-version={{aisearch_api_version}}
Content-Type: application/json
api-key: {{aisearch_key}}

{  
    "name": "{{datasource_name}}",
    "type": "azureblob",
    "credentials": {  
        "connectionString": "ResourceId=/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group_name}}/providers/Microsoft.Storage/storageAccounts/{{storage_account_name}};"
    },
    "container": {  
        "name": "{{container_name}}"
    },
    "dataChangeDetectionPolicy": {  
        "@odata.type": "#Microsoft.Azure.Search.HighWaterMarkChangeDetectionPolicy",
        "highWaterMarkColumnName": "metadata_storage_last_modified"  
    }
}