# Chat Completion - POST
@deployment-id = gpt-4o-2024-05-13
@apimApiVersion    = 2023-05-01-preview
@APIM-API-Endpoint = https://mmapim01.azure-api.net/balanced-azure-open-aiservice-api
@subscription-key = 05eaa4db36254d16acfef11ac413f335 

@APIM-API-Operation-Path = /openai/deployments/{{deployment-id}}/chat/completions?api-version={{apimApiVersion}}


POST {{APIM-API-Endpoint}}{{APIM-API-Operation-Path}}
api-key: {{subscription-key}}
Content-Type: application/json

{
  "max_tokens": 500,
  "messages": [
    {
      "role": "user",
      "content": "Hi there!"
    }
  ]
}