# Embedding creation - POST
@deployment-id = embeddings-for-apim
@apimApiVersion    = 2023-05-01-preview
@APIM-API-Endpoint = https://genaihackapim.azure-api.net
@APIM-API-Name = balanced-azure-openai-service-api
@APIM-API-Operation-Path = openai/deployments/{{deployment-id}}/embeddings

POST {{APIM-API-Endpoint}}/{{APIM-API-Name}}/{{APIM-API-Operation-Path}}?api-version={{apimApiVersion}}

POST {{APIM-API-Endpoint}}{{APIM-API-Operation-Path}}
api-key: {{apim_subscription_key_service}}
Content-Type: application/json

{
  "input": ["rabbit"]
}