# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api


@azure_deployment_name = gpt-4.1-for-apim
 # The version of the OpenAI API to use, could be different from the latest version, e.g. 2025-04-01-preview / 2025-04-28
@openai_api_version = 2025-04-28

###
# Invoking OpenAI
POST {{azure_openai_endpoint}}/openai/deployments/{{azure_deployment_name}}/chat/completions?api-version={{openai_api_version}}
Api-Key: {{azure_openai_apikey}}
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "What is a meaning function? Please summarize in less than 20 words."
        }
    ]
}