# az login --use-device-code --tenant <your-tenant-id-or-domain>
# az config set extension.dynamic_install_allow_preview=true
# az account tenant list --output table
# for Azure Management tasks --> az account get-access-token --resource https://management.core.windows.net/
# for OpenAI tasks --> az account get-access-token --resource https://cognitiveservices.azure.com/
# for Azure Search tasks --> az account get-access-token --resource https://search.azure.com/
# Recall to enable "API Access control" under "keys" to accept RBAC authentication"

@token = ****

@index  = srch-index-files
###
# Invoking AI Search to retrieve the list of data sources (key-based authentication)
GET {{aisearch_endpoint}}//datasources/?api-version={{aisearch_api_version}}
Api-Key: {{aisearch_api_key}}
Content-Type: application/json


###
# Invoking AI Search to retrieve the list of data sources (AAD-based authentication)
# The user needs to have the "Search Index Data Reader" or "Search Index Data Contributor" role to execute this request
GET {{aisearch_endpoint}}//datasources/?api-version={{aisearch_api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json


###
# Invoking AI Search to retrieve the result of a search query (RBAC authentication)
# The user needs to have the "Search Index Data Reader" or "Search Index Data Contributor" role to execute this request
POST {{aisearch_endpoint}}/indexes/{{index}}/docs/search?api-version={{aisearch_api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "search": "is chandler jelous of Monica for Richard?",
  "count": true,
  "vectorQueries": [
    {
      "kind": "text",
      "text": "is chandler jelous of Monica for Richard?",
      "fields": "chunkVector"
    }
  ],
  "queryType": "semantic",
  "semanticConfiguration": "my-semantic-config",
  "captions": "extractive",
  "answers": "extractive|count-3",
  "queryLanguage": "en-us",
  "select": "title, name"
}