# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az login --use-device-code --tenant <your-tenant-id-or-domain>
# az config set extension.dynamic_install_allow_preview=true
# az account tenant list --output table
# for Azure Management tasks --> az account get-access-token --resource https://management.core.windows.net/
# for Foundry Applications --> az account get-access-token --resource https://ai.azure.com/
# for OpenAI tasks --> az account get-access-token --resource https://cognitiveservices.azure.com/
# for Azure Search tasks --> az account get-access-token --resource https://search.azure.com/
# for Machine Learning tasks --> az account get-access-token --resource https://ml.azure.com/ 

@baseUrl = http://localhost:8088
# Dammi la lista delle cartelle del mio OneDrive, ordinata per dimensione decrescente (in Mb).
# What is a meaning function? Answer in less than 10 words.
@query = Dammi la lista delle cartelle del mio OneDrive, ordinata per dimensione decrescente (in Mb).

### plain un-authenticated request
POST {{baseUrl}}/responses
Content-Type: application/json
 
{
    "input": "{{query}}"
}


### un-authenticated request with OBO token without authorization header
POST {{baseUrl}}/responses
Content-Type: application/json
x-client-user-token: {{bearertoken_for_obo}}
 
{
    "input": "{{query}}"
}

### user-authenticated request with OBO token with authorization header
POST {{baseUrl}}/responses
Content-Type: application/json
Authorization: Bearer {{bearertoken_user-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
 
{
    "input": "{{query}}"
}

### app-authenticated request with OBO token with authorization header
POST {{baseUrl}}/responses
Content-Type: application/json
Authorization: Bearer {{bearertoken_app-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
 
{
    "input": "{{query}}"
}