# https://foundry7159.services.ai.azure.com/api/projects/aif7159-standard-agent-project, https://mm-ai-upskilling-project-resourc.services.ai.azure.com/api/projects/ai-upskilling-project

@foundry_project_endpoint = https://foundry7159.services.ai.azure.com/api/projects/aif7159-standard-agent-project

# asb-assistant-01 hello-world-python-responses hello-world-responses02
@agent_name = hello-world-responses02

# Dammi la lista delle cartelle del mio OneDrive, ordinata per dimensione decrescente (in Mb).
# What is a meaning function? Answer in less than 10 words.
# What can you do?
@query = Give me the list of my OneDrive folders, sorted by size decreasing (in Mb).


# The version of the Foundry Responses API to use. It should be v1 (better and latest) or 2025-11-15-preview
@version = {{azure_openai_responses_api_version}}


###
# Invoking Foundry Agent within a Foundry Project with RESPONSES APIs
# https://<account>.services.ai.azure.com/api/projects/<project>/agents/<agentName>/endpoint/protocols/openai/responsehttps://foundry7159.services.ai.azure.com/api/projects/aif7159-standard-agent-project/agents/ha02-agentserverresponses-llmagent/endpoint/protocols/openai/responses
# we can use either the user token or the app token for Foundry (bearertoken_user-token_for_foundry or bearertoken_app-token_for_foundry).
# The key point is that the invoker must have at least the "Foundry Agent Consumer" role assigned to the Foundry Agent or Project:
# https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry?tabs=owner%2Cfoundry#built-in-roles
POST {{foundry_project_endpoint}}/agents/{{agent_name}}/endpoint/protocols/openai/responses?api-version={{version}}
Authorization: Bearer {{bearertoken_user-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
Content-Type: application/json

{
    "input": "{{query}}"
}


### app-authenticated request with OBO token with authorization header
POST {{foundry_project_endpoint}}/agents/{{agent_name}}/endpoint/protocols/openai/responses?api-version={{version}}
Content-Type: application/json
Authorization: Bearer {{bearertoken_app-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
 
{
    "input": "{{query}}"
}

###


az role assignment create --assignee "b0cc68f2-87d7-491d-8cc2-60624256126e" \
  --role "eed3b665-ab3a-47b6-8f48-c9382fb1dad6" \
  --scope "/subscriptions/eca2eddb-0f0c-4351-a634-52751499eeea/resourceGroups/rg-aifoundry7159/providers/Microsoft.CognitiveServices/accounts/foundry7159/projects/aif7159-standard-agent-project"

az role assignment create --assignee "b0cc68f2-87d7-491d-8cc2-60624256126e" \
  --role "eed3b665-ab3a-47b6-8f48-c9382fb1dad6" \
  --scope "/subscriptions/eca2eddb-0f0c-4351-a634-52751499eeea/resourceGroups/rg-aifoundry7159/providers/Microsoft.CognitiveServices/accounts/foundry7159/projects/aif7159-standard-agent-project/agents/hello-world-python-responsesxxx"

az role assignment delete \
  --assignee "b0cc68f2-87d7-491d-8cc2-60624256126e" \
  --role "eed3b665-ab3a-47b6-8f48-c9382fb1dad6" \
  --scope "/subscriptions/eca2eddb-0f0c-4351-a634-52751499eeea/resourceGroups/rg-aifoundry7159/providers/Microsoft.CognitiveServices/accounts/foundry7159/projects/aif7159-standard-agent-project/agents/hello-world-python-responsesxxx"
