@agent_name = hello-world-python-responses

# Dammi la lista delle cartelle del mio OneDrive, ordinata per dimensione decrescente (in Mb).
# What is a meaning function? Answer in less than 10 words.
@query = Dammi la lista delle cartelle del mio OneDrive, ordinata per dimensione decrescente (in Mb).


###
# Invoking Foundry Agent within a Foundry Project with RESPONSES APIs
# https://<account>.services.ai.azure.com/api/projects/<project>/agents/<agentName>/endpoint/protocols/openai/responsehttps://foundry7159.services.ai.azure.com/api/projects/aif7159-standard-agent-project/agents/ha02-agentserverresponses-llmagent/endpoint/protocols/openai/responses
# we can use either the user token or the app token for Foundry (bearertoken_user-token_for_foundry or bearertoken_app-token_for_foundry).
POST {{foundry_project_endpoint}}/agents/{{agent_name}}/endpoint/protocols/openai/responses?api-version={{azure_openai_responses_api_version}}
Authorization: Bearer {{bearertoken_user-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
Content-Type: application/json

{
    "input": "{{query}}"
}


### app-authenticated request with OBO token with authorization header
POST {{foundry_project_endpoint}}/agents/{{agent_name}}/endpoint/protocols/openai/responses?api-version={{azure_openai_responses_api_version}}
Content-Type: application/json
Authorization: Bearer {{bearertoken_app-token_for_foundry}}
x-client-user-token: {{bearertoken_for_obo}}
 
{
    "input": "{{query}}"
}