# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az login --use-device-code --tenant <your-tenant-id-or-domain>
# az config set extension.dynamic_install_allow_preview=true
# az account tenant list --output table
# for Azure Management tasks --> az account get-access-token --resource https://management.core.windows.net/
# for Foundry Applications (aiazurecom) --> az account get-access-token --resource https://ai.azure.com/
# for OpenAI tasks --> az account get-access-token --resource https://cognitiveservices.azure.com/
# for Azure Search tasks --> az account get-access-token --resource https://search.azure.com/
# for Machine Learning tasks --> az account get-access-token --resource https://ml.azure.com/ 


@resource_group = rg-aifoundry7159

@foundry_account = foundry7159
@foundry_project = aif7159-standard-agent-project
@foundry_application = promptagent-01
@foundry_agent_published = promptagent-01
@foundry_agent_to_publish = promptagent-01
@api_version_for_openai = 2025-11-15-preview
@api_version_for_management = 2025-10-01-preview


###
# Invoking the agent through a Foundry Application REST call for OpenAI Responses API
POST https://{{foundry_account}}.services.ai.azure.com/api/projects/{{foundry_project}}/applications/{{foundry_application}}/protocols/openai/responses?api-version={{api_version_for_openai}}
Authorization: Bearer {{bearertoken_for_aiazurecom}}
Content-Type: application/json

{
    "input": "Tell me please which day is today, and what is the weather like in Seattle."
}

###
# Retrieve all Foundry Applications in a Foundry Project
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{foundry_account}}/projects/{{foundry_project}}/applications?api-version={{api_version_for_management}}
Authorization: Bearer {{bearertoken_for_azuremanagement}}
Content-Type: application/json


###
# Retrieve a specific Foundry Application in a Foundry Project
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{foundry_account}}/projects/{{foundry_project}}/applications/{{foundry_application}}?api-version={{api_version_for_management}}
Authorization: Bearer {{bearertoken_for_azuremanagement}}
Content-Type: application/json