# https://learn.microsoft.com/en-us/azure/ai-services/agents/quickstart?pivots=rest-api
# az login --use-device-code --tenant <your-tenant-id-or-domain>
"""
az logout
az login
APP_ID=1584713c-4129-46b7-b4c2-333df819ef5c; echo $APP_ID
APP_OBJ_ID=$(az ad app show --id 1584713c-4129-46b7-b4c2-333df819ef5c --query "id" -o tsv | tr -d '\r'); echo $APP_OBJ_ID
APP_ID_URI=$(az ad app show --id $APP_OBJ_ID --query "identifierUris[0]" -o tsv | tr -d '\r'); echo $APP_ID_URI
SCOPE_VALUE=$(az ad app show --id $APP_OBJ_ID --query "api.oauth2PermissionScopes[0].value" -o tsv | tr -d '\r'); echo $SCOPE_VALUE
TOKEN=$(az account get-access-token --scope "${APP_ID_URI}/${SCOPE_VALUE}" --query accessToken -o tsv); echo $TOKEN
"""

# Just if pre-authorization is needed, run this:
# Unique APP_ID for AZURE CLI
# AZURE_CLI_APP_ID="04b07795-8ddb-461a-bbee-02f9e1bf7b46"

# az rest --method PATCH \
#   --uri "https://graph.microsoft.com/v1.0/applications/$APP_OBJ_ID" \
#   --headers "Content-Type=application/json" \
#   --body "{
#     \"api\": {
#       \"preAuthorizedApplications\": [{
#         \"appId\": \"$AZURE_CLI_APP_ID\",
#         \"delegatedPermissionIds\": [\"$SCOPE_ID\"]
#       }]
#     }
#   }"

# either http://localhost:8000 or  http://localhost:8010 or https://mcp-onedrive-demo01.niceflower-8b4a0311.swedencentral.azurecontainerapps.io
@mcpBaseUrl = https://mcp-onedrive-demo01.niceflower-8b4a0311.swedencentral.azurecontainerapps.io



### get the list of tools - UN-AUTHENTICATED or FAKE-AUTEHTNCIATION, just to see the metadata of the tools
POST {{mcpBaseUrl}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Authorization: Bearer {{bearertoken_for_mcp}}

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "tools/list",
  "params": {}
}


### runs WhoAmI tool to verify the authentication and get the user info
POST {{mcpBaseUrl}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Authorization: Bearer {{bearertoken_for_mcp}}

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/call",
  "params": {"name":"WhoAmI","arguments":{}}
}


### runs create_ticket tool to verify the authentication and get the user info
POST {{mcpBaseUrl}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Authorization: Bearer {{bearertoken_for_mcp}}

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/call",
  "params": {"name":"create_ticket","arguments":{"description":"My computer is on fire"}}
}


### invoke an MCP tool (e.g. get_onedrive_root_folders)
POST {{mcpBaseUrl}}/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Authorization: Bearer {{bearertoken_for_mcp}}

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/call",
  "params": {"name":"get_onedrive_root_folders","arguments":{}}
}

### invoke MS Graph API directly, using the graph access token (not the MCP token)
GET https://graph.microsoft.com/v1.0/me/drive/root/children
Content-Type: application/json
Authorization: Bearer {{bearertoken_for_msgraph}}