@azfunction_host_name = raitvpiu-telemetry.rai.it


###
POST https://{{azfunction_host_name}}/api/RaiTvPiuSendTelemetry
Content-Type: application/json

{
  "telemetry": {
    "timestamp": "2022-03-10T00:00:00Z",
    "deviceId": "device001",
    "temperature": 25.5,
    "humidity": 50.0
  }
}