# $token=$(az account get-access-token --query accessToken --output tsv)

@Token==*******

@subscriptionId=*******
@resourceGroupName=*******
@apimName=*******
@backendId=*******
@backendBal1=*******
@backendBal2=*******

@apimApiVersion=2022-08-01

# Backend Pool - GET
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendId}}?api-version={{@apimApiVersion}}
Authorization: Bearer {{Token}}

###

# Backend Pool - PUT
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendId}}?api-version={{@apimApiVersion}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "type": "Microsoft.ApiManagement/service/backends",
  "name": "{{backendId}}",
  "properties": {
    "type": "Pool",
    "pool": {
      "services": [
        {
          "id": "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendBal1}}",
          "priority":1
        },
        {
          "id": "/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendBal2}}",
          "priority":2,
        }
      ]
    }
  }
}

### Backend Main - GET
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendBal1}}?api-version=2022-08-01
Authorization: Bearer {{Token}}

###

# Backend Pool - Main
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{apimName}}/backends/{{backendBal1}}?api-version=2023-05-01-preview
Authorization: Bearer {{Token}}
Content-Type: application/json

  {
    "properties": {
      "url": "https://*******.openai.azure.com/openai",
      "protocol": "http",
      "circuitBreaker": {
        "rules": [
          {
            "failureCondition": {
              "count": "1",
              "interval": "PT10S" ,
              "statusCodeRanges": [
                {
                  "min": "429",
                  "max": "429"
                }
              ]
            },
            "name": "myBreakerRule",
            "tripDuration": "PT1H",
            "acceptRetryAfter": "true"
          }
        ]
      }
    }
  }
}