# no bearer token required, just subscription key

@apim-api-version = 2024-05-01-preview
@backend-openai-pool-name = backend-openai-pool
# Balanced Azure OpenAI Service API
@apim_api_name = balanced-azure-openai-service-api
@deployment_id = gpt-4.1-for-apim

# apim_subscription_key_premium, apim_subscription_key_standard and apim_subscription_key_basic
@apim-subscription-key = {{apim_subscription_key_premium}}
###
POST {{apim_service_gatewayurl}}/{{apim_api_name}}/openai/deployments/{{deployment_id}}/chat/completions?api-version={{apim-api-version}}
api-key: {{apim-subscription-key}}
Content-Type: application/json

{
    "messages": [
      {
        "role": "user",
        "content": "What is a meaning function?"
      }
    ],
    "temperature": 0,
    "top_p": 1.0,    
    "max_tokens": 500
}